services:
  db:
    image: postgres:16
    container_name: rms-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  app:
    image: radhikas0812/reimbursement-app:v1
    container_name: rms-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      APP_SECURITY_JWT_HMAC-SECRET: ${JWT_SECRET}
      APP_SECURITY_JWT_ISSUER: rms-auth
      APP_SECURITY_JWT_EXPIRES-MIN: 60
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    expose:
      - "8080"   # internal only; Caddy talks to this
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: rms-caddy
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  pgdata:
  caddy_data:
  caddy_config:
