version: "3.8"

services:
  db:
    image: postgres:16
    container_name: rms-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # optional: expose DB for debugging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  app:
    image: radhikas0812/reimbursement-app:v1
    container_name: rms-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      APP_SECURITY_JWT_HMAC-SECRET: ${JWT_SECRET}
      APP_SECURITY_JWT_ISSUER: rms-auth
      APP_SECURITY_JWT_EXPIRES-MIN: 60
    ports:
      - "8080:8080"   # expose backend on host
    restart: unless-stopped

volumes:
  pgdata:
