version: "3.8"

services:
  db:
    image: postgres:16.3-alpine
    platform: linux/amd64
    container_name: rms-db
    environment:
      POSTGRES_DB: reimbursedb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: "RADhi@081215"   # quote because of special chars
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # optional: expose DB for debugging with DBeaver/psql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d reimbursedb"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  app:
    image: radhikas0812/reimbursement-app:v1
    container_name: rms-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,mappings
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/reimbursedb
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: "RADhi@081215"
      APP_SECURITY_JWT_HMAC-SECRET: "EmTAIbB2/tzdt798Ka6qtC6Epbm/nZespm2K+bRQ2kA="   # replace with your actual JWT secret
      APP_SECURITY_JWT_ISSUER: rms-auth
      APP_SECURITY_JWT_EXPIRES-MIN: 60

    ports:
      - "8080:8080"   # expose backend on host
    restart: unless-stopped

volumes:
  pgdata:
