services:
  db:
    image: postgres:16
    container_name: rms-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"   # expose to host for DBeaver; remove on server if not needed
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: rms-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
      SERVER_PORT: ${SERVER_PORT}
      # Datasource
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # JWT
      APP_SECURITY_JWT_HMAC-SECRET: ${JWT_SECRET}
      APP_SECURITY_JWT_ISSUER: rms-auth
      APP_SECURITY_JWT_EXPIRES-MIN: 60
      # (Optional) CORS via env if you wire it in config
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
